import sharp from 'sharp';
import path from 'path';
import fs from 'fs/promises';
import crypto from 'crypto';
import { config } from '../config';
import { AppError } from './errors';

const ALLOWED_MIME = ['image/jpeg', 'image/png', 'image/webp', 'image/gif'];
export const MAX_IMAGE_SIZE = 5 * 1024 * 1024; // 5MB
const MAX_DIMENSION = 1200;

export function isAllowedImageMime(mime: string): boolean {
  return ALLOWED_MIME.includes(mime);
}

export interface ProcessedImage {
  fileName: string;
  url: string;
  size: number;
}

/**
 * Processes an uploaded image: validates MIME (done by multer filter),
 * resizes to max 1200px and converts to WebP. The output name is always
 * generated by the server (UUID) so client-supplied names can never cause
 * path traversal.
 */
export async function processImage(
  buffer: Buffer,
  companyId: string,
  originalMime: string,
): Promise<ProcessedImage> {
  const dir = path.join(config.uploadsDir, companyId);
  await fs.mkdir(dir, { recursive: true });

  const fileName = `${crypto.randomUUID()}.webp`;
  const filePath = path.join(dir, fileName);

  try {
    // `animated: true` keeps animated GIF/WebP frames intact
    await sharp(buffer, { animated: originalMime === 'image/gif' })
      .resize(MAX_DIMENSION, MAX_DIMENSION, {
        fit: 'inside',
        withoutEnlargement: true,
      })
      .webp({ quality: 82 })
      .toFile(filePath);
  } catch {
    throw new AppError('Não foi possível processar a imagem. Use JPG, PNG, WebP ou GIF.', 400);
  }

  const stats = await fs.stat(filePath);

  return {
    fileName,
    url: `/uploads/${companyId}/${fileName}`,
    size: stats.size,
  };
}

/** Removes an image file from disk, ignoring missing files. */
export async function removeImageFile(url: string): Promise<void> {
  // Only accept our own URL shape: /uploads/<companyId>/<fileName>
  const match = /^\/uploads\/([A-Za-z0-9_-]+)\/([A-Za-z0-9_-]+\.webp)$/.exec(url);
  if (!match) return;

  const filePath = path.join(config.uploadsDir, match[1], match[2]);
  try {
    await fs.unlink(filePath);
  } catch {
    // file already gone — nothing to do
  }
}
